### ISSUE TITLE
Populate the harvard reference for all documents

### ISSUE THREAD

**Issue by JamieMaclean** [fire-library/openfire#29]
We now have the ability to create the harvard reference for all document. We are able to build it custom for each document and even recursively for documents that have many parts e.g. PD7974 or the Eurocodes. the function to update is `harvard_reference()` in this file `src-tauri/src/domain/impls.rs`

Keep in mind that the code in that function is a copy and paste of the `friendly_reference` function, so it is not necessarily built correctly. Functions may have to be created in the inner documents if it is called recursively. 

Let me know if any of this is not clear.

**Comment by simonsantama** [comment]
Two points here. 
1. I have populated the harvard references for most methods. However, currently, the subtitle in the home page shows the full harvard reference plus chapter number plus equation. It should be only the document reference (chapter and equation to be shown in the actual page or even the box). I've tried to change this but let me know how it looks.
2. Because of the way the they created the title for the 7974 documents, we need to chat about how we separate them. Right now, I think we need to treat them as entirely different documents

**Comment by JamieMaclean** [comment]
@simonsantama I think this can be closed no?

**Comment by simonsantama** [comment]
Yeh close and reject no?

**Comment by JamieMaclean** [comment]
No need to reject, it has been completed, so task can just be closed out.

**Comment by simonsantama** [comment]
Ah right. Yep. Got confused
